### PR TITLE
added teams url under a team name in teams section

### PR DESCRIPTION
**Pull request by sumitbishti**
fixes: #943 
Screenshot 2024-02-19 211732

Video Link: https://www.loom.com/share/35328504cf3f46e9be78bd485252e8dc?sid=1f309776-8b52-4af4-b86b-652b762fef5b

## Summary by CodeRabbit

- **Chores**
	- Updated export settings for UI components without altering functionality.

### CODE REVIEW

**Comment by dguyen** [comment]
You should be able to do all this with just css, no need for state or changes to `AvatarWithText` component

```html
{teams.map((team) => (
  <DropdownMenuItem asChild key={team.id}>
    <Link href={formatRedirectUrlOnSwitch(team.url)} className="group">
      <AvatarWithText
        avatarFallback={formatAvatarFallback(team.name)}
        primaryText={team.name}
        secondaryText={
          <>
            <span className="opacity group-hover:hidden">
              {formatSecondaryAvatarText(team)}
            </span>
            <span className="opacity-0 group-hover:opacity-100">{`/t/${team.url}`}</span>
          </>
        }
        rightSideComponent={
          isPathTeamUrl(team.url) && (
            <CheckCircle2 className="ml-auto fill-black text-white dark:fill-white dark:text-black" />
          )
        }
      />
    </Link>
  </DropdownMenuItem>
))}
```

Also would probably be nice to disable this feature if there's only 1 team.

**Comment by sumitbishti** [comment]
> Also would probably be nice to disable this feature if there's only 1 team.

i think we should keep it. It would be more consistent that way.

**Comment by dguyen** [comment]
The goal of this feature is to distinguish between duplicate names for teams, which is unlikely in the first place.

We expect the majority of people with teams to generally will have 1 team, and if they had more it would be unlikely to have duplicate names.

So it doesn't really make sense to have this for one team.

**Comment by sumitbishti** [comment]
no there are changes. I totally forgot to push them!!

**Comment by sumitbishti** [comment]
no actually there are changes. I'll push them shortly

**Comment by sumitbishti** [comment]
Hey @dguyen i have opened a new PR (#1122) for this. After processing that one you can close this.

**Pull request closed without merging**
