### PR TITLE
chore: update zod to 3.22.4

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Description:

- This PR updates zod to `3.22.4` as the previous versions had ReDoS vulnerability

More Info: https://github.com/colinhacks/zod/pull/2824 and https://github.com/colinhacks/zod/issues/2609

### CODE REVIEW

**Review by catalinpit — APPROVED** [review]
thanks!

**Review by dguyen — CHANGES_REQUESTED** [review]
Could you also upgrade them across the other packages? I think since a recent commit there were a few other packages that have zod now.

**Comment by adithyaakrishna** [comment]
@dguyen Yes sure, will send a commit for that too :)

**Comment by adithyaakrishna** [comment]
@dguyen Done, I updated `next-auth` as well, also, I was wondering if I could just update all the packages instead of only Zod?

**Comment by dguyen** [comment]
What was the reason for upgrading next-auth? We prefer to try stay away from unnecessary updates since they generally break things and requires testing.

In this case I think upgrading Zod only is fine since there's a vulnerability.

**Comment by adithyaakrishna** [comment]
@dguyen Makes sense, I have reverted the change to `next-auth` with the above commit :)

**Comment by dguyen** [comment]
Something in the package lock file is breaking the build.

When I delete it and re-run everything it works.

Could you undo everything, and do the Zod upgrade incrementally so the package lock file is correctly updated?

**Comment by dguyen** [comment]
Cheers 👍 

/tip 25

**Pull request merged**
