### PR TITLE
docs: fix typo in CONTRUBUTING.md

### PR DESCRIPTION
**Pull request by thara003**
# What?
This PR fixes a typo in CONTRIBUTING.md

before: 
Screenshot 2023-08-29 at 7 59 15 PM

# What changes I have made?

It should be "Select an issue from here or create a new one"

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by thara003** [comment]
Oops! Sorry for that,  I have submitted the form

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎉

**Comment by adithyaakrishna** [comment]
@thara003 There seems to be another grammatical issue here, https://github.com/documenso/documenso/blob/feat/refresh/README.md which needs to be changed into `To contribute, please see our contribution guide.`. Could you please let me know if you would be able to accommodate that in this PR as well?

Screenshot 2023-08-29 at 11 27 07 PM

**Review by adithyaakrishna — APPROVED** [review]
Thanks a lot, much appreciated 🥳

**Comment by Mythie** [comment]
Thanks Thara! 

thanks-pickle

**Review by Mythie — APPROVED** [review]

**Pull request merged**
