### PR TITLE
feat: add legend to pie chart

### PR DESCRIPTION
**Pull request by dephraiim**

### CODE REVIEW

**Comment by Mythie** [comment]
It looks like you've already accepted our Contributor License Agreement, thanks so much! :tada:

**Comment by Mythie** [comment]
Can I get a quick screenshot of the change 🙏🏻

**Comment by ElTimuro** [comment]
@dephraiim nice work. Maybe the font show not have the color of the segment tho, the light part is harder to read,

**Comment by dephraiim** [comment]
@ElTimuro how does this look?

CleanShot 2023-08-17 at 09 45 17@2x

**Comment by dephraiim** [comment]
Just pushed a change. This is the new look

CleanShot 2023-08-17 at 10 59 30@2x

**Review by Mythie — APPROVED** [review]

**Pull request merged**
