### PR TITLE
feat: add early adopters graph

### PR DESCRIPTION
**Pull request by dephraiim**

### CODE REVIEW

**Review by ElTimuro — COMMENTED** [review]
The scraper is called StargRazer, did you intentionally call it <BarMetric<StargazersType>?

**Comment by dephraiim** [comment]
@ElTimuro, I was using the same chart for both the github metrics and the early adopters and it was the same code through out so I refactored it into a reusable component as BarMetric to serve both the github graph and the early adopters

**Comment by ElTimuro** [comment]
> @ElTimuro, I was using the same chart for both the github metrics and the early adopters and it was the same code through out so I refactored it into a reusable component as BarMetric to serve both the github graph and the early adopters

Makes total sense, I was just talking about the "r" 😀

**Comment by dephraiim** [comment]
I'll take care of it. I made it Stargazer all round, I'll update it

**Comment by ElTimuro** [comment]
lgtm

**Comment by ElTimuro** [comment]
Syncing to documenso.next via 🫱

**Pull request merged**
