### PR TITLE
feat: add sticky behavior to pricing options container

### LINKED ISSUE #894: Better UX for showing pricing section in mobile
### Describe the improvement you are suggesting in detail

Currently, when we switch from monthly to yearly or vice versa in mobile, the user doesn't get to know what exactly changes because there is no movement or update on the screen. I'm attaching a video for reference. 

I feel we should scroll the user to the pricing section (where the amount is changed) if they switch between the monthly/yearly tabs. 

https://github.com/documenso/documenso/assets/28510494/7ea6d892-b754-4559-88d8-284dc155bd47

### Additional Information & Alternatives (optional)

_No response_

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by JuanSebastianM**
Fixes #894

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by JuanSebastianM** [comment]
> Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:
> 
> https://documen.so/cla

That's weird. I had filled out the form before. Anyway, just filled it out once again.

**Comment by dguyen** [comment]
Hi @JuanSebastianM!

It looks like this doesn't follow the design provided by our designer in the issue thread:

https://www.figma.com/file/2UpmlfgunLLbbyMImsTB3e/Pricing-page---mobile?type=design&node-id=0-922&mode=design

Could you please have a look to see if you can implement it?

**Comment by JuanSebastianM** [comment]
> Hi @JuanSebastianM!
> 
> It looks like this doesn't follow the design provided by our designer in the issue thread:
> 
> https://www.figma.com/file/2UpmlfgunLLbbyMImsTB3e/Pricing-page---mobile?type=design&node-id=0-922&mode=design
> 
> Could you please have a look to see if you can implement it?

It should be good now. Just FYI, things I added on the latest commit to match the design on Figma:
1. Changed periods menu alignment to the right on mobile devices.
2. The underline color of each period was changed to `bg-foreground` on mobile.

**Comment by Mythie** [comment]
Looks good to me! Happy first contribution Juan 🚀

lgtm-spongebob

**Review by Mythie — APPROVED** [review]

**Pull request merged**
