### PR TITLE
Add husky & lint staged

### PR DESCRIPTION
**Pull request by nsylke**
I didn't noticed an issue for this yet, but I did read the blog post about adding it - so this PR implements husky & lint-staged to ensure all future commits are formatted. There are a few ways of configuring lint-staged, I just took the straightforward approach, happy to change it - if preferred.

Additionally, I modified the Dockerfile to disable husky from being installed. You'll see something along the lines of this in the docker build logs when installing dependencies, indicating its been disabled.
```bash
. prepare$ husky install
. prepare: husky - HUSKY env variable is set to 0, skipping install
. prepare: Done
```

### CODE REVIEW

**Comment by Mythie** [comment]
Hey Nicholas, great work! You beat me to creating the issues surrounding those items 😅 

As for the configuration it's preferred to use `lint-staged.config.cjs` so we can do some fancy things later on with other file types 🚀

**Comment by nsylke** [comment]
@Mythie Certainly! Would you like that to be in its own package similar to prettier and then require it?

**Comment by Mythie** [comment]
It can just sit in the root of the monorepo for now 😁

**Comment by nsylke** [comment]
Updated to use `lint-staged.config.cjs`. I noticed prettier (`npm run format`) isn't formatting any of the `cjs` files, is this intentional?

**Comment by Mythie** [comment]
> Updated to use `lint-staged.config.cjs`. I noticed prettier (`npm run format`) isn't formatting any of the `cjs` files, is this intentional?

It's an oversight on my behalf, definitely feel free to update it as part of this 😄

**Comment by nsylke** [comment]
@Mythie Just adding `cjs`, or would you also like to have `js`, `mjs`, `cts`, `mts` and `mdx` as well to future proof it? Also, I just noticed we are formatting md where I think that was meant to be `mdx`.

**Comment by Mythie** [comment]
> @Mythie Just adding `cjs`, or would you also like to have `js`, `mjs`, `cts`, `mts` and `mdx` as well to future proof it? Also, I just noticed we are formatting `md` where I think that was meant to be `mdx`.

Future proofing sounds great! I pray we never step into ESM hell but if we do it’ll be a lifesaver.

**Comment by nsylke** [comment]
Hah, I definitely agree with that. Anyways, should be all good now!

**Review by Mythie — APPROVED** [review]

**Comment by nsylke** [comment]
Resolved conflicts

**Comment by nsylke** [comment]
I noticed when I pulled the parent to resolve the conflicts I used lockfile version 2 instead of 3. I just fixed that. I'm used to using pnpm, so didn't even realize a new version of the lockfile was released. 😓

**Review by Mythie — APPROVED** [review]

**Comment by Mythie** [comment]
Thanks for your contribution Nicholas! We will now have some level of standard formatting on commits before they go up saving us some time 🎉 

thanks-pickle

**Pull request merged**
