### PR TITLE
fix: dashboard logo

### PR DESCRIPTION
**Pull request by dephraiim**
Screenshot 2023-05-29 at 08 02 16

### CODE REVIEW

**Comment by Mythie** [comment]
I thought it used to have both the logo and wordmark? 🤔

**Comment by dephraiim** [comment]
This is from an old branch

Screenshot 2023-05-29 at 09 11 16

**Comment by doug-andrade** [comment]
There's room in the nav bar for it. 

Consider keeping both the logo mark and text on desktop, and hiding the text on mobile.

`hidden sm:block`

**Comment by dephraiim** [comment]
By using just the logo, you can achieve a cleaner design. I feel the text of that size in addition is distracting,

**Review by Mythie — APPROVED** [review]

**Pull request merged**
