### PR TITLE
feat: add user conversion count to admin panel

### PR DESCRIPTION
**Pull request by ephraimduncan**
## Description

Display the count of users who signed up after signing at least one document in the admin panel

CleanShot 2024-05-09 at 21 44 59@2x

## Changes Made

- Created a new function `getSignerConversion` to retrieve the count of converted recipients from the database and  added a new metric card in the admin stats page to display the count

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [ ] I have added/updated tests that prove the effectiveness of these changes.
- [ ] I have updated the documentation to reflect these changes, if applicable.
- [x] I have followed the project's coding style guidelines.
- [ ] I have addressed the code review feedback from the previous submission, if applicable.

## Summary by CodeRabbit

- **New Features**
  - Introduced `SignerConversionChart` component to display signer conversion data in a bar chart.
  - Added `FileCog`, `UserPlus`, and `Users` icons to the admin stats page.

- **Enhancements**
  - Updated `Users` icon in admin navigation bar for a consistent visual experience.
  - Enhanced `metric-card` styling with improved text spacing.
  - `SignerConversionChart` now supports cumulative data display.

- **Bug Fixes**
  - Corrected inconsistent icon usage on the admin stats page.

- **Chores**
  - Implemented functions to fetch signer conversion statistics for more detailed analytics.

### CODE REVIEW

**Review by ElTimuro — COMMENTED** [review]
The SQL logic looks correct

**Review by ElTimuro — COMMENTED** [review]
@ephraimduncan checked locally as well, looks good
you can go ahead and add the monthly

**Review by ElTimuro — CHANGES_REQUESTED** [review]
- Looks good
- We just should remove the card, its redundant

**Comment by Mythie** [comment]
Want to take a crack at migrating the `queryRaw` to Kysely? We should also include something for the conversion query to only include those who received a document within the last 30 days or so which would imply correlation.

**Comment by ephraimduncan** [comment]
@Mythie I took a shot at Kysely. Let me know what you think.

**Review by Mythie — APPROVED** [review]

**Pull request merged**
