### PR TITLE
Add subscriptions

### PR DESCRIPTION
**Pull request by Mythie**
Adds subscription functionality to Documenso to handle the community plan for our upcoming production launch.

### CODE REVIEW

**Comment by ElTimuro** [comment]
- @Mythie Billing should be hidden when not enabled

**Comment by ElTimuro** [comment]
@Mythie Billing should be hidden when not enabled

**Comment by Mythie** [comment]
Still need to fill in a few lorems, hoping you can help with that 😄

**Comment by ElTimuro** [comment]
- @Mythie this looks nice
- tested and worked locally
- merging for further manual testing

**Pull request merged**
