### PR TITLE
Add tooltip to recipients action buttons

### LINKED ISSUE #144: Hide Resend Button until Document is sent
The `resend` button on the reciepents page is disabled until the document is sent to the recipient.

Screenshot 2023-05-05 at 13 36 37

In my opinion, the `resend` button does not provide any significant functionality until the document is sent and only serves to clutter the interface. 

I propose that we remove the button until the document is sent simplify the interface.

### PR DESCRIPTION
**Pull request by piyushkrmaurya**
Fixes #144

### CODE REVIEW

**Review by dephraiim — COMMENTED** [review]
👍

**Review by dephraiim — CHANGES_REQUESTED** [review]
Can you please take a look at this too in addition to this change?

https://github.com/documenso/documenso/issues/144#issuecomment-1539638611

**Review by dephraiim — CHANGES_REQUESTED** [review]
Can you please take a look at this too in addition to this change?

https://github.com/documenso/documenso/issues/144#issuecomment-1539638611

**Comment by piyushkrmaurya** [comment]
"Edit" button should be removed when status is "Completed", instead of disabling it. I will add this change.

**Review by dephraiim — APPROVED** [review]

**Comment by piyushkrmaurya** [comment]
image

**Comment by piyushkrmaurya** [comment]
This looks quite messy. I guess we can separate out the action buttons in a separate menu something like this:

image

image

image

If this looks good, I will update the PR.

**Comment by piyushkrmaurya** [comment]
On mobile phones, hovering is not possible. So, you can't see the popover without clicking it.

**Comment by piyushkrmaurya** [comment]
Added the popover on both resend and delete button,  and added a confirm dialog on delete button.

image

image

image

image

**Comment by piyushkrmaurya** [comment]
image

**Comment by Mythie** [comment]
Love the work! Just checking out the code now for final verification before I can hit the ✅ button

**Comment by Mythie** [comment]
So I have two final changes to make sadly 😿 

First I wanted to add an animation to the tooltip since it's so cool:

```diff
--- a/packages/ui/components/tooltip/Tooltip.tsx
+++ b/packages/ui/components/tooltip/Tooltip.tsx
@@ -1,4 +1,5 @@
 import React, { useState } from "react";
+import { classNames } from "@documenso/lib";
 
 export function Tooltip(props: any) {
   let timeout: NodeJS.Timeout;
@@ -16,19 +17,19 @@ export function Tooltip(props: any) {
   };
 
   return (
-    <div
-      className="relative"
-      onPointerEnter={showTip}
-      onPointerLeave={hideTip}
-    >
+    <div className="relative" onPointerEnter={showTip} onPointerLeave={hideTip}>
       {props.children}
-      {active && (
-        <div className="absolute left-1/4 -translate-x-1/2 bottom-9 transform px-4">
-          <span className="text-xs inline-block py-1 px-2 rounded text-neon-800 bg-neon-200">
-            {props.label}
-          </span>
-        </div>
-      )}
+
+      <div
+        className={classNames(
+          "absolute left-1/4 -translate-x-1/2 transform px-4 duration-300",
+          active && "bottom-9 opacity-100",
+          !active && "pointer-events-none bottom-6 opacity-0"
+        )}>
+        <span className="text-neon-800 bg-neon-200 inline-block rounded py-1 px-2 text-xs">
+          {props.label}
+        </span>
+      </div>
     </div>
   );
-};
+}
-- 
```

Second I don't want to hide the edit button on the documents listing but instead disable it as it used to be:

```diff
--- a/apps/web/pages/documents.tsx
+++ b/apps/web/pages/documents.tsx
@@ -143,7 +143,7 @@ const DocumentsPage: NextPageWithLayout = (props: any) => {
           </div>
         </div>
         <div className="mt-3 mb-12 flex flex-row-reverse items-center gap-x-4">
-          <div className="pt-5 block w-fit">
+          <div className="block w-fit pt-5">
             {filteredDocuments.length != 1 ? filteredDocuments.length + " Documents" : "1 Document"}
           </div>
           <SelectBox
@@ -221,13 +221,13 @@ const DocumentsPage: NextPageWithLayout = (props: any) => {
                         <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                           {document.title || "#" + document.id}
                         </td>
-                        <td className="whitespace-nowrap inline-flex py-3 gap-x-2 gap-y-1 flex-wrap max-w-[250px] text-sm text-gray-500">
+                        <td className="inline-flex max-w-[250px] flex-wrap gap-x-2 gap-y-1 whitespace-nowrap py-3 text-sm text-gray-500">
                           {document.Recipient.map((item: any) => (
                             <div key={item.id}>
                               {item.sendStatus === "NOT_SENT" ? (
                                 <span
                                   id="sent_icon"
-                                  className="flex-shrink-0 h-6 inline-flex items-center rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800">
+                                  className="inline-flex h-6 flex-shrink-0 items-center rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800">
                                   {item.name ? item.name + " <" + item.email + ">" : item.email}
                                 </span>
                               ) : (
@@ -237,7 +237,7 @@ const DocumentsPage: NextPageWithLayout = (props: any) => {
                                 <span id="sent_icon">
                                   <span
                                     id="sent_icon"
-                                    className="flex-shrink-0 h-6 inline-flex items-center rounded-full bg-yellow-200 px-2 py-0.5 text-xs font-medium text-yellow-800">
+                                    className="inline-flex h-6 flex-shrink-0 items-center rounded-full bg-yellow-200 px-2 py-0.5 text-xs font-medium text-yellow-800">
                                     <EnvelopeIcon className="mr-1 inline h-4"></EnvelopeIcon>
                                     {item.name ? item.name + " <" + item.email + ">" : item.email}
                                   </span>
@@ -250,7 +250,7 @@ const DocumentsPage: NextPageWithLayout = (props: any) => {
                                 <span id="read_icon">
                                   <span
                                     id="sent_icon"
-                                    className="flex-shrink-0 h-6 inline-flex items-center rounded-full bg-yellow-200 px-2 py-0.5 text-xs font-medium text-yellow-800">
+                                    className="inline-flex h-6 flex-shrink-0 items-center rounded-full bg-yellow-200 px-2 py-0.5 text-xs font-medium text-yellow-800">
                                     <CheckIcon className="-mr-2 inline h-4"></CheckIcon>
                                     <CheckIcon className="mr-1 inline h-4"></CheckIcon>
                                     {item.name ? item.name + " <" + item.email + ">" : item.email}
@@ -261,7 +261,7 @@ const DocumentsPage: NextPageWithLayout = (props: any) => {
                               )}
                               {item.signingStatus === "SIGNED" ? (
                                 <span id="signed_icon">
-                                  <span className="flex-shrink-0 h-6 inline-flex items-center rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800">
+                                  <span className="inline-flex h-6 flex-shrink-0 items-center rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800">
                                     <CheckBadgeIcon className="mr-1 inline h-5"></CheckBadgeIcon>{" "}
                                     {item.email}
                                   </span>
@@ -303,17 +303,17 @@ const DocumentsPage: NextPageWithLayout = (props: any) => {
                         </td>
                         <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                           <div>
-                            {document.status !== "COMPLETED" && (
-                              <IconButton
-                                icon={PencilSquareIcon}
-                                className="mr-2"
-                                onClick={(event: any) => {
-                                  event.preventDefault();
-                                  event.stopPropagation();
-                                  router.push("/documents/" + document.id);
-                                }}
-                              />
-                            )}
+                            <IconButton
+                              icon={PencilSquareIcon}
+                              className="mr-2"
+                              onClick={(event: any) => {
+                                event.preventDefault();
+                                event.stopPropagation();
+                                router.push("/documents/" + document.id);
+                              }}
+                              disabled={document.status === DocumentStatus.COMPLETED}
+                            />
+
                             <IconButton
                               icon={ArrowDownTrayIcon}
                               className="mr-2"
```

Unfortunately I can't make these changes against your remote as it's protected so I kindly ask that you make these final changes so we can get this across the line 🙏

**Comment by piyushkrmaurya** [comment]
Thanks for the appreciation.
Reverted the edit button changes to disable instead of hiding.

Made some changes to the animation. It didn't seem to work because the div itself was getting removed from the render tree, and transition class was missing. Adding a preview video of the animation:

https://github.com/documenso/documenso/assets/34208835/3414f6fd-1f82-452e-992d-384dff7849fe

**Pull request merged**
