### PR TITLE
small fix for recipient-selector

### PR DESCRIPTION
**Pull request by SauravL3010**
ListBox options must be unique

|  |  preview |
| ------- | --- | 
| Before | 086b7e6baaea9f3e92ac67ed36f0af53|
| After | 0df1e45febd95bc11dbc704a1c20032e|

P.s this is my first commit to the repo, so just wanted to start with something small.

### CODE REVIEW

**Comment by Mythie** [comment]
Awesome first contribution! The recipient selector not showing the correct recipients was a small point of frustration for me the other day so I'm glad to see it fixed 😄 

Thanks for working on this and welcome to Documenso!

**Comment by ElTimuro** [comment]
@SauravL3010 great work, thanks for your first contribution 🎉
@Mythie this was part of your PR if I remember correctly. I would like to merge this already so we can test it, works for you?

**Review by ElTimuro — APPROVED** [review]
Approved for merge if alright for @Mythie

**Comment by Mythie** [comment]
Of course, the sooner things go in the better 😄

**Comment by ElTimuro** [comment]
> Of course, the sooner things go in the better 😄

This is the way

**Comment by ElTimuro** [comment]
@SauravL3010  congrats on your first merge. The code is being built and deployed to test.documenso.com as we speak

**Pull request merged**
