### PR TITLE
fix: background color of signature page

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/documenso/documenso/issues/483

Screenshot 2023-10-02 at 2 24 11 PM

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by dephraiim** [comment]
The color of the text, `Clear Signature` does not match with the rest of the text on the page, can you update it?

**Comment by Udit-takkar** [comment]
Screenshot 2023-10-02 at 7 54 51 PM

done

**Comment by dguyen** [comment]
@Mythie for the majority of SignaturePads we wrap it with a `Card` to have the gradient

Should we do this for all SignaturePads? Or are those generally for special cases?

**Comment by dguyen** [comment]
@Udit-takkar thanks!

/tip 25

**Pull request merged**
