### PR TITLE
fix: completed/pending status gets incremented once if sender is one of the recipients

### LINKED ISSUE #853: Bug: Completed and Pending status gets incremented twice when Sender is one of the Recipients
### Issue Description

When you send a doc to yourself and sign it. Completed gets incremented twice.
When you send a doc to yourself and others, and only you sign it. Pending gets incremented twice.

### Steps to Reproduce

1. send a doc to yourself and sign it.
2. send a doc to yourself and one other, and only you sign it.

### Expected Behavior

Completed and Pending status should not be incremented twice when sender is one of the recipient.

### Current Behavior

Completed and Pending status is gettting incremented twice when sender is one of the recipient.

### Screenshots (optional)

Here T is the sender and E and T are the Recipients. And T has signed the doc.
Screenshot 2024-01-21 230337

Here E is the sender and the Recipient too. And E has signed the doc.
Screenshot 2024-01-20 222917

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

_No response_

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by sumitbishti**
completed/pending status gets incremented once if sender is one of the recipients

fixes #853

### CODE REVIEW

**Comment by Mythie** [comment]
Would this also be applicable for the `notSignedCounts` as well? Change looks good otherwise 😎

**Comment by sumitbishti** [comment]
> Would this also be applicable for the `notSignedCounts` as well? Change looks good otherwise 😎

No, i don't think so,  because we are using ```notSignedCounts``` just to calculate the count of Inbox. Which is getting incremented at only one place. Unlike pending and completed, which were getting incremented once under ```ownerCounts``` and again under ```hasSignedCounts```

**Comment by dguyen** [comment]
Would it make sense to extract the duplicate queries within the OR statement to outside it like so?

```
      where: {
        User: {
          email: {
            not: user.email,
          },
        },
        OR: [
          {
            status: ExtendedDocumentStatus.PENDING,
            Recipient: {
              some: {
                email: user.email,
                signingStatus: SigningStatus.SIGNED,
              },
            },
            deletedAt: null,
          },
          {
            status: ExtendedDocumentStatus.COMPLETED,
            Recipient: {
              some: {
                email: user.email,
                signingStatus: SigningStatus.SIGNED,
              },
            },
          },
        ],
      },
```

**Comment by sumitbishti** [comment]
> Would it make sense to extract the duplicate queries within the OR statement to outside it like so?
> 
> ```
>       where: {
>         User: {
>           email: {
>             not: user.email,
>           },
>         },
>         OR: [
>           {
>             status: ExtendedDocumentStatus.PENDING,
>             Recipient: {
>               some: {
>                 email: user.email,
>                 signingStatus: SigningStatus.SIGNED,
>               },
>             },
>             deletedAt: null,
>           },
>           {
>             status: ExtendedDocumentStatus.COMPLETED,
>             Recipient: {
>               some: {
>                 email: user.email,
>                 signingStatus: SigningStatus.SIGNED,
>               },
>             },
>           },
>         ],
>       },
> ```

yup totally

**Review by dguyen — APPROVED** [review]
Looks good to me, thank you :)

**Pull request merged**
