### PR TITLE
fix: added constants for theme variables

### PR DESCRIPTION
**Pull request by plxity**
fixes: #776

### CODE REVIEW

**Comment by dguyen** [comment]
Could you please also update these ones as well?

https://github.com/documenso/documenso/blob/main/apps/web/src/components/(dashboard)/common/command-menu.tsx#L218-L220

**Comment by plxity** [comment]
@dguyen done!

**Comment by plxity** [comment]
@catalinpit Please review this change

**Comment by Mythie** [comment]
Hey Apoorv, most of the Documenso team are on break over the next couple of days due to many upcoming National Holidays. 

We’ll be with you when we can, until then please avoid tagging team members 🙌🏻

**Comment by plxity** [comment]
Apologies @Mythie! Happy holidays 🎉

**Review by dguyen — APPROVED** [review]
Looks good to me, thanks 🙂

**Pull request merged**
