### PR TITLE
fix: increase e2e test timeout

### PR DESCRIPTION
**Pull request by pablopaul**
Double e2e test timeout to fix flakiness

### CODE REVIEW

**Comment by Mythie** [comment]
Seems this is still angry, I guess I better do my actual job 🤡

**Comment by pablopaul** [comment]
@Mythie one more test timeout, therefor I increased the timeout event further. Also I added video logs and tried to fix the artifact upload step, lets see 👍

**Comment by pablopaul** [comment]
@Mythie I need to run this locally, the initial fix did not help

**Comment by Mythie** [comment]
Tada! Thanks for the help Paul and happy first contribution 🤗 

thank-you-stronk

**Review by Mythie — APPROVED** [review]

**Pull request merged**
