### PR TITLE
refactor: used constant for steps instead of strings

### LINKED ISSUE #750: Use constants instead of strings in the step involved inside widget component
### Improvement Description

As of now, strings are directly getting used for the steps in `apps/marketing/src/components/(marketing)/widget.tsx` component like `EMAIL, NAME, SIGN`. We can use a constant object for different steps involved.

### Rationale

Using a constant object would keep the code clean and customisable if we need any other step in future or need to change the step name, the only change would be there in the constant object and not the complete file. 

### Proposed Solution

We can use a constant object like
```js
export const STEP = {
  EMAIL: 'EMAIL',
  NAME: 'NAME',
  SIGN: "SIGN"
} as const;

```

### Alternatives (optional)

_No response_

### Additional Context

_No response_

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by plxity**
fixes #750

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by plxity** [comment]
@Mythie Done

**Comment by plxity** [comment]
@Mythie Please review this whenever you are available.

**Review by catalinpit — APPROVED** [review]

**Comment by catalinpit** [comment]
Thanks for the PR! Great work!

**Pull request merged**
