### PR TITLE
fix: update validation message of clear signature input

### PR DESCRIPTION
**Pull request by anikdhabal**
In single Player Mode after clearing a signature from the signature field, it displays "Expected string, received null."

before:-

Screenshot 2023-11-21 040842

### CODE REVIEW

**Comment by catalinpit** [comment]
Hey! Thanks for the PR! Can you update the branch, please?

**Comment by anikdhabal** [comment]
> Hey! Thanks for the PR! Can you update the branch, please?

I've updated it.

**Comment by catalinpit** [comment]
I just tested the changes locally and I keep getting this error. Did it work for you?

CleanShot 2023-12-06 at 10 58 02@2x

After reverting the change, it works normally.

**Comment by anikdhabal** [comment]
> I just tested the changes locally and I keep getting this error. Did it work for you?
> 
> CleanShot 2023-12-06 at 10 58 02@2x
> 
> After reverting the change, it works normally.

But it is working fine for me. 
Screenshot 2023-12-07 224537

**Comment by catalinpit** [comment]
> > I just tested the changes locally and I keep getting this error. Did it work for you?
> > CleanShot 2023-12-06 at 10 58 02@2x
> > After reverting the change, it works normally.
> 
> But it is working fine for me. Screenshot 2023-12-07 224537

Can you try the following steps, please?

1. Add a document
2. Add a signature field
3. Try to press `Continue` without adding the signature
4. Get the error and then add the signature
5. Try to sign it and finish the process

Let me know after you try it, please.

**Comment by anikdhabal** [comment]
> > > I just tested the changes locally and I keep getting this error. Did it work for you?
> > > CleanShot 2023-12-06 at 10 58 02@2x
> > > After reverting the change, it works normally.
> > 
> > 
> > But it is working fine for me. Screenshot 2023-12-07 224537
> 
> Can you try the following steps, please?
> 
> 1. Add a document
> 2. Add a signature field
> 3. Try to press `Continue` without adding the signature
> 4. Get the error and then add the signature
> 5. Try to sign it and finish the process
> 
> Let me know after you try it, please.

Okk

**Comment by Mythie** [comment]
Had a play and this seems to have been resolved, sorry for the massive delay in this one 😓

**Pull request closed without merging**
