### PR TITLE
feat: copy and paste fields

### PR DESCRIPTION
**Pull request by ephraimduncan**
## Description

 Allow users to copy and paste fields using keyboard shortcuts.

CleanShot 2024-06-22 at 15 56 04

## Changes Made
- Implemented the `onFieldCopy` and `onFieldPaste` callback functions to handle copy and paste operations.
- Added event listeners for keyboard shortcuts (Ctrl+C, Ctrl+V, Ctrl+D) to copy, paste, and duplicate fields.

## Testing Performed
- Tested the copy and paste functionality with various field types in different scenarios.
- Ran unit tests for the `add-fields` component to ensure no regressions.
- Manually tested on browsers Chrome, Firefox, and Safari to ensure compatibility.

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [x] I have added/updated tests that prove the effectiveness of these changes.
- [x] I have updated the documentation to reflect these changes, if applicable.
- [x] I have followed the project's coding style guidelines.
- [x] I have addressed the code review feedback from the previous submission, if applicable.

## Summary by CodeRabbit

- **New Features**
  - Implemented copy and paste functionality for form fields.
  - Added keyboard shortcuts for copying (Ctrl+C), pasting (Ctrl+V), and duplicating (Ctrl+D) fields.
  - Introduced a duplicate action for individual field items.

- **Enhancements**
  - Improved state management for tracking the last active field in forms.
  - Enhanced user interface with consistent styling and new duplicate buttons for field items.
  - Updated code formatting experience for TypeScript React files with Prettier as the default formatter.

### CODE REVIEW

**Comment by Mythie** [comment]
This is super interesting, any thoughts on how we can surface this to users so they know they can use native copy and paste to duplicate fields?

I feel like we're probably also going to need to include a UI version of this for non power users.

**Comment by ephraimduncan** [comment]
> any thoughts on how we can surface this to users so they know they can use native copy and paste to duplicate fields?

- Show a tooltip when they hover over a field
- Display a pop-up message, like when adding a username for the first time
- Show a quick toast right after adding the first field

> I feel like we're probably also going to need to include a UI version of this for non power users.

I had some ideas on this.
- Add a right-click menu with a "Duplicate" option
- or put a "Duplicate" icon next to the delete icon on each field

**Comment by Mythie** [comment]
With the landing of the advanced fields I reckon we can go the little popup menu option to duplicate in addition to the current field handlers.

Currently where we have the remove and "advanced settings" options we can add a duplicate one as well that will dump a copy of the field a given offset from the current field `+20px`?

**Comment by ephraimduncan** [comment]
CleanShot 2024-07-24 at 20 41 18

**Comment by Mythie** [comment]
Looks great!

**Review by Mythie — APPROVED** [review]

**Comment by ephraimduncan** [comment]
Keanu Ship It

**Pull request merged**
