### PR TITLE
fix: [DOC-296] Add changesets for automatic release versioning

### LINKED ISSUE #268: [DOC-296] Add changesets for automatic release versioning
Following the work on the `feat/refresh` branch we will be in a state where we're releasing more often at which time versioning will become a large painpoint.

To alleviate this we would like to add [changesets](https://github.com/changesets/changesets) to our project which should help automatically determine versioning based on the commit history between releases.

Additionally we hope to use changesets for the generation of release notes which will be improved via the usage of conventional commits [DOC-295](https://linear.app/documenso/issue/DOC-295/add-commitlint-for-linting-of-commit-messages) #267

I personally have used [Lerna](https://github.com/lerna/lerna) in the past for a similar purpose but given we've opted to use turborepo for this project it's no longer relevant.

We are open to alternate tools to use but they must be able to do the above in a semi-painless fashion.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-296](https://linear.app/documenso/issue/DOC-296/add-changesets-for-automatic-release-versioning)</sub>

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #268 
/claim #268

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by rishi-raj-jain** [comment]
Done!

**Comment by Mythie** [comment]
Very quick turnaround Rishi, can you update the PR to show example of it having done its thing?

This can include logs from your console as to what it would upgrade given a certain fake change alongside any release notes it might create.

An added bonus would be a section in the README on how to use it for that purpose but it's not mandatory 😄

**Comment by rishi-raj-jain** [comment]
Sure thing! I'll record a demo ✨ and upload

**Comment by rishi-raj-jain** [comment]
https://github.com/documenso/documenso/assets/46300090/f95a1897-6f0b-4273-b0c9-c970f7b70504

**Comment by rishi-raj-jain** [comment]
https://github.com/documenso/documenso/assets/46300090/e73598ba-397f-49ca-948d-009447a7e2c3

**Comment by rishi-raj-jain** [comment]
@Mythie I think it's all setup now. Do let me know if anything.

**Comment by rishi-raj-jain** [comment]
> An added bonus would be a section in the README on how to use it for that purpose but it's not mandatory 😄

What else shall I add? Happy to contribute.

**Comment by Mythie** [comment]
It looks all good on our end! 😄 

Great job on the quick turnaround

**Review by Mythie — APPROVED** [review]

**Pull request merged**
