### PR TITLE
feat: added a better theme change ability for user

### PR DESCRIPTION
**Pull request by captain-Akshay**
I noticed some anomaly in the theme section for user so added a dropdownmenusub for better user experience which will be more acceptable to user
example:-
image

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by captain-Akshay** [comment]
Done! 👍🏻

**Comment by captain-Akshay** [comment]
this is the new look 
image

**Comment by captain-Akshay** [comment]
@Mythie @ElTimuro @fmerian do let me know if any change is required or your review will be highly appreciated!!

**Comment by Mythie** [comment]
Hey there, I'm happy to go with a dropdown for theming but the dropdown item should also have an icon otherwise it appears out of place with the other menu items.

Please consider which icon we could use for it 😄

**Comment by captain-Akshay** [comment]
image
thanks for the review @Mythie how's this one let me know what you think !

**Comment by Mythie** [comment]
Looks good to me! Thanks for your contribution 🫶🏻

lgtm-spongebob

**Pull request merged**
