### PR TITLE
added state for handling multiple api call issue for changing name

### PR DESCRIPTION
**Pull request by captain-Akshay**
This pull request fixes the issue described in #364 

The issue was that the code was making multiple API calls when the user changed their name. This has been fixed by adding a state to track the user's name and a few if checks to prevent unnecessary API calls.

- preventing multiple API calls
- enhancing user experience

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by captain-Akshay** [comment]
i actually already did that @Mythie ! really looking forward for the review for this PR and any changes if required.

**Comment by captain-Akshay** [comment]
@dephraiim @Mythie @ElTimuro it would be great if you can review my code! highly appreciated!!

**Comment by Mythie** [comment]
Apologies, closing this as we're now all in on the new codebase. We still appreciate the effort that was put in and are sorry that this didn't make it.

We'll work on our communication to avoid this in the future 🫶🏻

**Pull request closed without merging**
