### PR TITLE
feat: S3Client: Add forcePathStyle

### PR DESCRIPTION
**Pull request by Hexcah**
I tried to resolve issue [#1048](https://github.com/documenso/documenso/issues/1048)

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by Mythie** [comment]
Changes look good, I'd suggest perhaps adding an additional comment in the `.env.example` that explains that this will change it from using virtual hosts `<bucket>.domain.com/<path>` to fully qualified paths `domain.com/<bucket>/<path>`

**Comment by Hexcah** [comment]
No problem I added that :)

**Review by Mythie — DISMISSED** [review]

**Comment by Mythie** [comment]
Cheers, everything else looks good to me! Happy first PR 🎉 

captain-america-salute

**Review by Mythie — APPROVED** [review]

**Comment by jasjastone** [comment]
Hello @Mythie 
Sorry to bother you, but am running minio on localhost(docker to be specific) and the end point URL is http://192.168.1.149:9000 the ip is the ip of my local computer and minio is accessible on the web and i have created a bucket name documenson but in documenson doesn't seems to work

here is the example request to **http://localhost:3000/api/v1/documents**
{
  "title": "Testing title",
  "externalId": "1234",
  "recipients": [
    {
      "name": "James",
      "email": "james@example.com",
      "role": "SIGNER"
    },
    {
      "name": "Stivie",
      "email": "stivie@example.com",
      "role": "SIGNER"
    }
  ],
  "meta": {
    "subject": "Testing",
    "message": "Test docu",
    "timezone": "Etc/UTC",
    "redirectUrl": "http://127.0.0.1:8000/app/sign-request",
    "signingOrder": "PARALLEL"
  },
  "authOptions": {
    "globalAccessAuth": "ACCOUNT",
    "globalActionAuth": "ACCOUNT"
  },
  "formValues": {}
}
return this response

{
  "message": "An error has occured while uploading the file"
}
here is the documenson variables for s3 on env
"NEXT_PUBLIC_UPLOAD_TRANSPORT=s3",
"NEXT_PRIVATE_UPLOAD_ENDPOINT=http://192.168.1.149:9000",
"NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=true",
"NEXT_PRIVATE_UPLOAD_REGION=unknown",
"NEXT_PRIVATE_UPLOAD_BUCKET=documenso",
"NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=documenson@123",
"NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=documenson@123",

Your guidance is appreciated

**Pull request merged**
