### PR TITLE
feat: add docker support and docker-compose quickstart

### PR DESCRIPTION
**Pull request by Mythie**
Add support for production container builds using the provided `Dockerfile` and `build.sh` script. This can later be used with actions to automatically publish to the provided docker registry.

Additionally, support an accelerated developer quickstart using `docker-compose`. Developers can now run the `dx` npm command to quickly spin up a database and mail server.

Partially fulfils #54

### CODE REVIEW

**Comment by Mythie** [comment]
This will need a follow-up task to optimise the current `package.json` deps so production builds can be much smaller, currently it's a bit grim:

```
→ docker images | grep documenso
documenso    0.1.0                                      7e902d7e82b7   3 minutes ago   744MB
documenso    00a18045f97ce70b5c93ec1e50aa69d17ff68405   7e902d7e82b7   3 minutes ago   744MB
documenso    e3db462587009437566a1829357ab87b2df7785b   4f909ec55405   2 hours ago     774MB
```

**Review by dephraiim — APPROVED** [review]
This is really great

**Comment by ElTimuro** [comment]
- "npm run dx" does now work on on windows. Is that a windows issue the I have to fix or can sth. be done to avoid this?
- Windows requires escaped reverse backslashes like this \\ instead of /.
- Should we just keep it Mac/ Linux first?

image

**Comment by ElTimuro** [comment]
Looks good, windows wise. Just can't connect yet, but could be me. @Mythie did it work for you connecting?

**Review by ElTimuro — APPROVED** [review]
Tested and working well 🚀

**Comment by treed593** [comment]
Working well in Github actions for me on a fork as well

 https://github.com/pennerc/documenso/pkgs/container/documenso

**Pull request merged**
