### PR TITLE
feat: return fields in GET /documents/:id endpoint

### PR DESCRIPTION
**Pull request by Etrenak**
## Description

To be able to use the PATCH `/api/v1/documents/{id}/fields/{fieldId}` endpoint, we need to know the fields ID of a particular document. The issue #1178 suggested to create a new endpoint for this. To be consistent with the `/templates` endpoint, I propose in this PR to directly add the `fields` field to the `/documents/:id` endpoint.

## Related Issue

This is related to #1178 but it might still be interesting to create a new endpoint which could also return the `fieldMeta`.

## Changes Made

Added `fields` to `ZSuccessfulGetDocumentResponseSchema` in the API contract, and changed the implementation accordingly.

## Testing Performed

- Tested on a document with and without fields.
- Full production build (`npm run build`)

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [ ] I have added/updated tests that prove the effectiveness of these changes.
- [ ] I have updated the documentation to reflect these changes, if applicable.
- [x] I have followed the project's coding style guidelines.
- [ ] I have addressed the code review feedback from the previous submission, if applicable.

## Summary by CodeRabbit

- **New Features**
	- Enhanced API response to include additional field data associated with documents.
	- Introduced a new schema for field objects, improving data validation and structure in API responses.

- **Chores**
	- Restructured schema definitions for better organization and readability.

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by Mythie** [comment]
This one looks good, I'll just need to grab a moment to run through the testing on this one manually!

**Comment by Etrenak** [comment]
For my use case, I would like to be able to also get fieldMeta returned by this endpoint. However, when I tried to also return the fieldMeta, I encountered some typing issues.

That is, I simply added fieldMeta in the schema like this :
```typescript
export const ZSuccessfulGetDocumentResponseSchema = ZSuccessfulDocumentResponseSchema.extend({
  recipients: z.lazy(() => z.array(ZSuccessfulRecipientResponseSchema)),
  fields: ZFieldSchema.pick({
    id: true,
    recipientId: true,
    type: true,
    page: true,
    positionX: true,
    positionY: true,
    width: true,
    height: true,
  }).extend({
    fieldMeta: ZFieldMetaSchema,
  }).array(),
});
```

But since fieldMeta in only known as a JsonValue in the prisma schema, we cannot simply return the result of the query to the database. Please tell me if this is OK to simply do the parsing of the database result in `implementation.ts:getDocument` into a correct field meta type ? I think it would be better to edit the database schema to indicate that the type is one of the advanced fields meta (Either TEXT meta, or DROPDOWN meta, ...), but it is certainly not the easiest way.

Do you know why it was chosen to store the field meta as a JsonValue in the database, and which of the two solutions I should prefer ?

**Comment by Etrenak** [comment]
So I ended up adding it anyway. I hope I did not waste your time on previously testing the PR without fieldMeta.

I also put back the definition of `ZFieldSchema` in its original position, since I learned what `z.lazy()` does (I'm not really familiar with TS). Using `z.lazy()` seems to mess up the OpenAPI schema generation though :frowning_face:. It only displays `fields: "string"` instead of the correct schema, but that's not a big issue.

Feel free to tell me if you would like another implementation, my precedent comment still stands.

**Review by catalinpit — APPROVED** [review]

**Comment by Etrenak** [comment]
Hey, I see this has been approved. Any idea when it might get merged ? Thanks!

**Review by Mythie — APPROVED** [review]

**Pull request merged**
