### PR TITLE
fix: fixed highlight issue in recipient selection, search bar, theme change

### PR DESCRIPTION
**Pull request by sumitbishti**
fixes: #920

### CODE REVIEW

**Comment by Mythie** [comment]
Could you please attach a set of images or video demo'ing the changes 😇

**Comment by dguyen** [comment]
Hey @sumitbishti, we're fine with how the standard command menu highlights the first item. It lets users use arrow keys to select what they want.

The main issue here is that the for the recipient roles dropdown, the highlighted item should be the currently selected recipient, not the first item.

**Comment by sumitbishti** [comment]
@dguyen okay i will just keep the changes related to recipient dropdown then. 
But what about the change theme dialog box? It wrongly shows the first (Light theme) item, when dark/system themes are currently applied.

**Comment by dguyen** [comment]
> But what about the change theme dialog box? It wrongly shows the first (Light theme) item, when dark/system themes are currently applied.

It's not wrong, because the global search command feature isn't intended for that, it's meant to show what's available.

Whereas the recipient dropdown is specifically meant to show the current selected recipient.

**Pull request closed without merging**
