### PR TITLE
replace neon with zinc-800

### PR DESCRIPTION
**Pull request by PeerRich**
neon has not enough contrast and is damaging a11y.

before a full-time designer is on board, I would prefer to use default colors that have a good color palette 

before:

CleanShot 2023-04-16 at 13 22 37@2x

after:

CleanShot 2023-04-16 at 13 22 26@2x

CleanShot 2023-04-16 at 13 26 55@2x

### CODE REVIEW

**Comment by ElTimuro** [comment]
- True and the black and white looks really clean.
- Would be nice to keep neon somewhere as a splash of color
- If I can't come up with something better, this could be the Launch Version for now

**Comment by PeerRich** [comment]
found some issues with background. fixing

**Comment by PeerRich** [comment]
keeping neon here:
CleanShot 2023-04-16 at 13 48 34@2x

**Comment by PeerRich** [comment]
i think neon as BG is fine with dark font on it.

but neon should not be used as text on white

**Comment by ElTimuro** [comment]
> i think neon as BG is fine with dark font on it.
> 
> but neon should not be used as text on white

That's true. Maybe Buttons with dark text?

**Comment by Mythie** [comment]
But I like inflicting blindness upon myself 😄 

I think we could look at reducing the intensity of the neon so it can continue being used in a more general fashion on dark text.

I'll pop open the old WGAG colorpicker shortly.

**Comment by ElTimuro** [comment]
@Mythie I would like to keep the neon for now, since we are new and edgy. But the buttons should have dark font and here should be no texts in neon on white like "signup here". Also Neon icons should have a dark background.

Like Penta, just more minimal an way less messy:

image

**Comment by Mythie** [comment]
Closing for now since we love blinding lights! Avert thy eyes @PeerRich 
blinding-lights

**Pull request closed without merging**
