### PR TITLE
replace float with flex

### PR DESCRIPTION
**Pull request by PeerRich**
float?

### CODE REVIEW

**Comment by ElTimuro** [comment]
Much appreciated 🚀

**Comment by PeerRich** [comment]
CleanShot 2023-04-16 at 13 39 13@2x
couldnt find this in the UI yet

**Comment by ElTimuro** [comment]
Looks great, testing and merging

**Comment by Mythie** [comment]
Closing as I dealt with this in #139 thanks for the hot ~~chips~~ tips!
hot-chips

**Comment by PeerRich** [comment]
#pain

**Comment by PeerRich** [comment]
😆

**Pull request closed without merging**
