### PR TITLE
feat: signup password hint

### LINKED ISSUE #954: feat: signup password hint
### Feature Description

Show password hints in the signup password field. I think if we add the hint just below the password field, then the form will be too long in our case.

So, we can add a popup-type feature when focusing on the password field.

similar kind of this:-

Screenshot 2024-02-21 213935

### Use Case

_No response_

### Proposed Solution

_No response_

### Alternatives (optional)

_No response_

### Additional Context

_No response_

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #954

https://github.com/documenso/documenso/assets/81948346/3e2dfb95-5f31-4cf6-8aec-503b20229557

## Summary by CodeRabbit

- **New Features**
  - Introduced a "Hinted Password" input component with interactive password strength validation hints.

- **Enhancements**
  - Updated password fields in sign-up forms to provide real-time feedback on password strength and criteria compliance.

- **Refactor**
  - Standardized password schema naming and replaced obsolete components with new hinted password input components.

### CODE REVIEW

**Comment by prajwalkulkarni** [comment]
As per the React docs, it is advised to use `useEffect` [to synchronize the component](https://react.dev/reference/react/useEffect) with an external system. Since no synchronizations are being done here, I believe the code in the effect handler can be extracted out and conditionally executed in the component, i.e., the validation can run whenever the input is changed and the user has focused on the input field. This way we can get rid of the `useEffect`. What do you think?

**Comment by adithyaakrishna** [comment]
@anikdhabal The in-built schema validation is giving errors due to the changes to `password-input.tsx` file. I've also attached the screenshots below for reference

**Sign up:**

Screenshot 2024-03-01 at 13 35 29

**Sign in:**

Screenshot 2024-03-01 at 13 34 17

**Comment by anikdhabal** [comment]
> @anikdhabal The in-built schema validation is giving errors due to the changes to `password-input.tsx` file. I've also attached the screenshots below for reference
> 
> **Sign up:**
> 
> Screenshot 2024-03-01 at 13 35 29
> **Sign in:**
> 
> Screenshot 2024-03-01 at 13 34 17

Hey @adithyaakrishna thanks for the review. I've fixed it.

**Comment by anikdhabal** [comment]
cc @Mythie @dguyen

**Comment by anikdhabal** [comment]
> Some feedback on the design, I haven't looked at the code yet:
> 
> * This doesn't really work with many resolutions since it'll overflow out of the screen, especially with the new sign up form design
> * The arrow symbol should probably match the color of the tooltip on light theme
> 
> Maybe have a look at the `PopOver` primitive?

Thank you for the review. We can move the tooltip to the left side from the right as it is overflows in the new design. Additionally, I will fix the arrow symbol.

**Comment by anikdhabal** [comment]
@dguyen This pr is now ready for review. I've made some changes.

**Comment by anikdhabal** [comment]
@Mythie any update on this one?

**Comment by anikdhabal** [comment]
@dguyen @adithyaakrishna any update on this one?

**Comment by anikdhabal** [comment]
@dguyen anu updates on this?

**Pull request closed without merging**
