### PR TITLE
chore: rename "none" document access to "no restrictions"

### LINKED ISSUE #1137: Rename document access "None" to "No restrictions"
### Describe the improvement you are suggesting in detail

The word "none" for the access just feels weird. Feels like no-one has access to it :smile: 

image

This is why I suggest renaming it to "Anyone with the link" like Google Docs has:
image

**EDIT**: Changed my mind to "No restrictions" as per [comment](https://github.com/documenso/documenso/pull/1138#issuecomment-2099723958)

### Additional Information & Alternatives (optional)

_No response_

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by raikasdev**
## Description

Renames the "None" document access option to "Anyone with the link".
image
image

## Related Issue

Fixes #1137

## Changes Made

- Renames the "None" document access option label

## Testing Performed

Tested on my local envinronment. Well, it's only changing a label and a tooltip text :smile: 

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [x] I have added/updated tests that prove the effectiveness of these changes.
- [x] I have updated the documentation to reflect these changes, if applicable.
- [x] I have followed the project's coding style guidelines.
- [x] I have addressed the code review feedback from the previous submission, if applicable.

## Summary by CodeRabbit

- **New Features**
	- Updated placeholder and display text for global authentication access and action selections to improve clarity, changing "None" to "No restrictions."
	- Enhanced tooltip content to reflect updated terminology for better user understanding.

### CODE REVIEW

**Comment by dguyen** [comment]
Hey! We like the wording with "Anyone with the link" but from a users perspective it might be confusing since to them it appears to just an email not a link

Whereas Google Docs is an actual link you copy

What do you think about "No Restrictions" instead?

**Comment by raikasdev** [comment]
> Hey! We like the wording with "Anyone with the link" but from a users perspective it might be confusing since to them it appears to just an email not a link
> 
> Whereas Google Docs is an actual link you copy
> 
> What do you think about "No Restrictions" instead?

That's great also! Gonna edit the PR later today

**Review by ElTimuro — COMMENTED** [review]
- Looks good
- The action authentication could say "No authentication" but that's a matter of taste I guess

**Comment by raikasdev** [comment]
> * Looks good
> * The action authentication could say "No authentication" but that's a matter of taste I guess

It's in the tooltip, so it should match the option imo.

**Comment by ElTimuro** [comment]
> > * Looks good
> > * The action authentication could say "No authentication" but that's a matter of taste I guess
> 
> It's in the tooltip, so it should match the option imo.

Not sure I get it, but as I said it's fine as it is :)

**Review by Mythie — DISMISSED** [review]

**Review by Mythie — APPROVED** [review]

**Comment by Mythie** [comment]
LGTM 
thanks-a-bunch

**Pull request merged**
