### PR TITLE
loading fonts with next/font for no layout shift

### LINKED ISSUE #169: Load fonts with `next/font` for no layout shift
https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

Source: https://github.com/documenso/documenso/blob/main/apps/web/styles/tailwind.css#L15-L40

### PR DESCRIPTION
**Pull request by doug-andrade**
Fixes #169 

Tested it locally and it builds without issues.

https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css

### CODE REVIEW

**Comment by ElTimuro** [comment]
Nice, this has been bothering me. /signup and /login don't get Montserrat anymore though:
image
image

**Comment by doug-andrade** [comment]
> Nice, this has been bothering me. /signup and /login don't get Montserrat anymore though:
> 
> image
> 
> image
> 
> 

The issue is due to the fonts being loaded in layout which login/signup aren't utilizing.

@ElTimuro , Would it be okay to lift the <main> from layout.tsx to _app.tsx as a wrapper for the entire app?

**Comment by doug-andrade** [comment]
**Fixed:** @ElTimuro 
Screenshot 2023-05-30 at 2 36 03 AM
Screenshot 2023-05-30 at 2 35 54 AM
Screenshot 2023-05-30 at 2 35 49 AM

**Comment by Mythie** [comment]
Awesome work Doug, I expect no less from you 😎

shawn-the-sheep

**Pull request merged**
