### PR TITLE
feat: add myself as signer

### PR DESCRIPTION
**Pull request by catalinpit**
## Description

This PR introduces the ability to add oneself as a signer by simply clicking a button, rather than filling the details manually.

### "Add Myself" in the document creation flow

https://github.com/documenso/documenso/assets/25515812/0de762e3-563a-491f-a742-9078bf1d627d

### "Add Myself" in the document template creation flow

https://github.com/documenso/documenso/assets/25515812/775bae01-3f5a-4b24-abbf-a47b14ec594a

## Related Issue

Addresses [#113](https://github.com/documenso/backlog-internal/issues/113)

## Changes Made

Added a new button that grabs the details of the logged-in user and fills the fields *(email, name, and role)* automatically when clicked.

## Testing Performed

Tested the changes locally through the UI.

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [ ] I have added/updated tests that prove the effectiveness of these changes.
- [ ] I have updated the documentation to reflect these changes, if applicable.
- [x] I have followed the project's coding style guidelines.
- [ ] I have addressed the code review feedback from the previous submission, if applicable.

## Summary by CodeRabbit

- **New Features**
	- Introduced the ability for users to add themselves as signers within documents seamlessly.
- **Enhancements**
	- Improved form handling logic to accommodate new self-signer functionality.
	- Enhanced user interface elements to support the addition of self as a signer, including a new "Add myself" button and disabling input fields during the process.

### CODE REVIEW

**Review by ephraimduncan — DISMISSED** [review]

**Comment by dguyen** [comment]
image

Initial testing shows issues with:
- Inability to adjust the current user recipient role and auth
- UI issues with the advanced checkbox, maybe drop it down to it's own line?

**Comment by catalinpit** [comment]
> image
> Initial testing shows issues with:
> 
> * Inability to adjust the current user recipient role and auth
> * UI issues with the advanced checkbox, maybe drop it down to it's own line?

Thanks for the feedback! My UI doesn't look like your UI (see videos from above + I just checked now locally again). Even after pulling the changes from main. I don't see the "Inherit authentication method" field and "Show advanced settings".

Regarding adjusting the recipient role, will update that.

**Comment by catalinpit** [comment]
Made the changes and this is how it looks now.


https://github.com/documenso/documenso/assets/25515812/061cd494-2a09-47e6-872f-cf6ea41f674f

**Review by dguyen — APPROVED** [review]
Cheers

**Pull request merged**
