### PR TITLE
fix: pagination discrepancy

### PR DESCRIPTION
**Pull request by Gautam-Hegde**
- This PR fixes the pagination discrepancy in the `DataTablePagination` component.
ref #1021

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by dguyen** [comment]
What do you think about doing this instead if we want to display 1 of 1?

```
Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount() || 1}
```

**Comment by Gautam-Hegde** [comment]
> What do you think about doing this instead if we want to display 1 of 1?
> 
> ```
> Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount() || 1}
> ```

Clean!!

**Review by Mythie — APPROVED** [review]

**Comment by Mythie** [comment]
lgtm! 🎉

**Pull request merged**
