### PR TITLE
feat: update the README for the self-hosting users

### PR DESCRIPTION
**Pull request by olivierlambert**
Fixing https://github.com/documenso/documenso/issues/589

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Review by catalinpit — APPROVED** [review]
looks good to me! thanks a lot!

**Comment by ElTimuro** [comment]
Hey @olivierlambert,

Thanks for contributing to Malfunction Mania, we really appreciate it 🫡

With your contribution, you earned the limited edition Malfunction Mania "Glitchy" shirt. DM me on  [twitter.com/eltimuro](http://twitter.com/eltimuro) or [timur@documenso.com](mailto:timur@documenso.com) to claim your perk 🎁

image

**Comment by Mythie** [comment]
Fantastic work thanks Olivier! 🎉

**Pull request merged**
