### PR TITLE
chore: minor lint fixes

### PR DESCRIPTION
**Pull request by dephraiim**

### CODE REVIEW

**Comment by Mythie** [comment]
What does prettier think of this?

**Comment by dephraiim** [comment]
> What does prettier think of this?

Can you clarify? `think` in what sense exactly?

**Comment by Mythie** [comment]
I noticed that you used oxc for this, so if we merge is prettier going to tell me that it needs to change back to the prior form?

**Comment by dephraiim** [comment]
Nope

**Review by Mythie — APPROVED** [review]

**Pull request merged**
