### PR TITLE
fix: username min length + fixed condition

### LINKED ISSUE #981: Username min length description does not match schema
### Issue Description

when registering a username, if you enter exactly 6 characters you will get back an error
`Only subscribers can have a username shorter than 6 characters`

technically 6 characters is not **shorter** than 6 characters, and based on the error message its safe to assume 6 characters should be accepted

when validating the username we check if `username.length <= 6` meaning only 7 or more characters will be true

the check is here: https://github.com/documenso/documenso/blob/3b8b87a90b8689f01d66b8e86330288940a1401d/packages/trpc/server/auth-router/router.ts#L28 

### Steps to Reproduce

signup, enter a 6 character string as username

### Expected Behavior

for 6 character strings to be accepted

### Current Behavior

6 character strings are rejected

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

_No response_

### Version [e.g., 2.0.1]

_No response_

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by McPizza0**
fixed #981 

`url.length <= 6` >>> `url.length < 6`

also removed debug message from the form component

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by jc00ke** [comment]
Hi there, I just ran into this while signing up. Am I right to assume it hasn't been deployed yet?

**Comment by ElTimuro** [comment]
> Hi there, I just ran into this while signing up. Am I right to assume it hasn't been deployed yet? 

- @jc00ke, we are looking into this.
- Happy to update your user and give you the name you wanted, go give me the go ✅

**Comment by jc00ke** [comment]
@ElTimuro ☑️🙏🏼

**Comment by ElTimuro** [comment]
https://github.com/documenso/documenso/pull/1144/files

**Comment by ElTimuro** [comment]
@jc00ke i added you claimed name ✅

**Pull request merged**
