### PR TITLE
fix: put max height in teams section in profile dropdown

### PR DESCRIPTION
**Pull request by sumitbishti**
fixes: #942 

Screenshot 2024-02-17 182156
Screenshot 2024-02-17 182138
Screenshot 2024-02-17 182048

### CODE REVIEW

**Comment by anikdhabal** [comment]
Hey @sumitbishti I think the theme is missing from the dropdown menu.

**Comment by dguyen** [comment]
Can you base the max screen height using screen height instead?

**Comment by sumitbishti** [comment]
> Hey @sumitbishti I think the theme is missing from the dropdown menu.

This is how it is...

**Review by dguyen — APPROVED** [review]
Cheers :)

**Pull request merged**
