### PR TITLE
feat: add google as auth provider 

### PR DESCRIPTION
**Pull request by doug-andrade**
Added Google as a provider in Next Auth.

**Please Note:**

- Prisma Schema was changed
- Mainly the `User.id` is now a `cuid()`
- References to `User.id` as a `number` or `int` have been changed to string.
- In some places I has to assert `User.email!`, I am not sure why but NextAuth's example for the Prisma Adapter allows the email to be nullable: `email   String?   @unique` [Prisma Adapter Reference](https://authjs.dev/reference/adapter/prisma)
- You need to create credentials in the Google Cloud Console. 

 **Configuration** [Google Provider Reference](https://next-auth.js.org/providers/google)

Create Credentials - https://console.developers.google.com/apis/credentials

The "Authorized redirect URIs" used when creating the credentials must include your full domain and end in the callback path. 

>Examples:
For production: `https://{YOUR_DOMAIN}/api/auth/callback/google`
For development: `http://localhost:3000/api/auth/callback/google`

**Video:**
https://www.loom.com/share/2ff960207bbd442e881cbee5ae6366a0

**Build Result:**
```bash
web % npm run build

> @documenso/web@0.1.0 build
> next build

...
...
...

Route (app)                                Size     First Load JS
┌ ○ /                                      135 B          77.6 kB
├ λ /dashboard                             0 B                0 B
├ λ /documents                             0 B                0 B
├ λ /documents/[id]                        0 B                0 B
├ λ /settings                              0 B                0 B
├ λ /settings/billing                      0 B                0 B
├ λ /settings/password                     0 B                0 B
├ λ /settings/profile                      0 B                0 B
├ ○ /signin                                0 B                0 B
└ ○ /signup                                0 B                0 B
+ First Load JS shared by all              77.5 kB
  ├ chunks/7fd0f9f1-3fb3dc3e14815666.js    50.5 kB
  ├ chunks/9-cf592fc7a319a8e7.js           24.4 kB
  ├ chunks/main-app-9a6c377ca6c4fdfa.js    211 B
  └ chunks/webpack-51fa59e154539451.js     2.33 kB

Route (pages)                              Size     First Load JS
┌ ○ /404                                   178 B          86.7 kB
├ λ /api/auth/[...nextauth]                0 B            86.5 kB
├ λ /api/claim-plan                        0 B            86.5 kB
├ λ /api/document/create                   0 B            86.5 kB
├ λ /api/stripe/webhook                    0 B            86.5 kB
└ λ /api/trpc/[trpc]                       0 B            86.5 kB
+ First Load JS shared by all              86.5 kB
  ├ chunks/main-c32231f5001c0b96.js        84 kB
  ├ chunks/pages/_app-415a5670032b79f5.js  190 B
  └ chunks/webpack-51fa59e154539451.js     2.33 kB

ƒ Middleware                               22.9 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

### CODE REVIEW

**Comment by doug-andrade** [comment]
**Added Avatar Image to Header:**
avatar example

**Comment by Mythie** [comment]
Love the work on this one, sadly changing from `Int` to `cuid` isn't in the books for the initial refresh as that will be harder to migrate.

Current goals are to refresh the code without changing the entity types where possible so a migration can be planned without any downtime 😄 

Happy to let this sit as I plan how we can achieve this though!

**Comment by doug-andrade** [comment]
@Mythie after doing some research, it looks like I would be able to implement the Google Provider with no changes to the prisma.schema.

I'd like to pursue this alternate implementation further if that's more what you're looking for.

**Comment by Mythie** [comment]
Closing as we now have #207 merged

**Pull request closed without merging**
