### PR TITLE
fix: update icons

### LINKED ISSUE #358: Request to Update Twitter Icon to X
## Issue Description
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

## Steps to Reproduce

1. Step 1: Go to footer section and see twitter old lcon

## Expected Behavior
The Twitter logo should be changed to X.

## Current Behavior
Not updated to X

## Screenshots (optional)
Screenshot 2023-09-07 170443

## Environment

- OS: [e.g., Windows 10]
- Browser: [e.g., Chrome, Firefox]
- Version: [e.g., 2.0.1]

## Checklist

- [✅] I have searched the existing issues to make sure this is not a duplicate.
- [✅] I have provided steps to reproduce the issue.
- [✅] I have included relevant environment information.
- [✅] I have included any relevant screenshots.
- [✅] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #358 
Update footer and mobile navigation icons.
As Lucide Icon is not supporting any brand icons and also twitter new icon, so I've updated it to react-icons.

Screenshot 2023-09-29 183046

### CODE REVIEW

**Comment by anikdhabal** [comment]
cc @Mythie @dephraiim

**Comment by dguyen** [comment]
Hello @anikdhabal!

I believe there are also 2 other areas where the lucide Github icons are being used, could you please also update those with the react-icons to maintain consistency?

**Comment by anikdhabal** [comment]
> Hello @anikdhabal!
> 
> I believe there are also 2 other areas where the lucide Github icons are being used, could you please also update those with the react-icons to maintain consistency?

Thanks for your review. Let me update that. I've updated the github and twitter icons to other areas.

**Comment by dguyen** [comment]
@anikdhabal thanks for your contribution!

/tip 20

**Pull request merged**
