### PR TITLE
fix: expired slack link

### PR DESCRIPTION
**Pull request by dephraiim**

### CODE REVIEW

**Comment by Mythie** [comment]
We should use the shortlink for this: https://documen.so/slack 😄

**Comment by dephraiim** [comment]
Does the short link redirect to the new invite link?

**Comment by Mythie** [comment]
> Does the short link redirect to the new invite link?

Sure does :smile:

**Review by Mythie — APPROVED** [review]

**Comment by Mythie** [comment]
Thanks Ephraim! 😄

**Pull request merged**
