### PR TITLE
fix: fix for Accepting signatures or text fields with white space only  #551

### LINKED ISSUE #551: [Bug]  Accepting signatures with white space only
Accepting signatures with white space only

## Issue Description

https://documenso.com/  On this page while filling in the signature we can fill it with space only so it looks blank. it is not correct.

## Steps to Reproduce
1. go to https://documenso.com/ 
2. In the third step where we fill our signatures fill it with  space only
## Expected Behaviour
We should fill at least one non-whitespace character. Spaces at starting and ending should be trimmed or should not be allowed

## Current Behavior

We can proceed to the next step without filling in a valid signature.

## Screenshots (optional)

https://github.com/documenso/documenso/assets/145282438/45cda900-65be-49ea-b2aa-8bb914498872

## Environment

- OS: ubuntu 22
- Browser: Chrome Version 117.0.5938.132 (Official Build) (64-bit)

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

### PR DESCRIPTION
**Pull request by Abhinav-Developer-23**
fixes #551 
There are multiple places where text fields can be filled with white space only.
In this PR I have fixed on 4 pages. Please find the working demo video.

https://stg-marketing.documenso.com/  (both signature and name)
https://stg-marketing.documenso.com/pricing  (when we click on signup now)
regular sign up page  (http://localhost:3000/signup)
profile page (http://localhost:3000/settings/profile)

https://github.com/documenso/documenso/assets/145282438/58ec4dca-0bfc-44ed-95db-51fbbd0ab394

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by Abhinav-Developer-23** [comment]
I have already filled out the CLA. 



Screenshot from 2023-10-14 02-48-23

**Comment by Abhinav-Developer-23** [comment]
I have updated the validation error messages.

**Comment by dguyen** [comment]
Looks good to me, thanks!

/tip 30

**Pull request merged**
