### PR TITLE
fix: resolve conflicting z-index values btwn avatar in document list and header

### LINKED ISSUE #870: Conflicting z-index between avatar in document list and header
### Issue Description

The avatar component within the document list has the same z-index value as the header component, causing the avatar to be above the header. When two elements have the same z-index value, the last one takes priority!

### Steps to Reproduce

Access the list of documents with 15 or more items

### Expected Behavior

image

### Current Behavior

image

Captura de Tela 2024-01-25 às 15 09 22

I think increasing the header z-index value by 10 (the current one is 50) is ok!

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

_No response_

### Version [e.g., 2.0.1]

_No response_

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by joselimadev**
## Description

This pull request solves the problem where the avatar component within the document list has the same z-index value as the header component, causing the avatar to be above the header. When two elements have the same z-index value, the last one takes priority!

## Related Issue
Fixes #870 

## Changes Made

1. Increases the value of the header's `z-index` by `10` (the current value is `50`)

### Mobile
image

### Browser
image

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by joselimadev** [comment]
@Mythie I've accepted the contributor license :)

**Comment by joselimadev** [comment]
I found another thing to adjust! 

The user menu must have the same z-index value the header.

image

**Comment by joselimadev** [comment]
Done

https://github.com/documenso/documenso/assets/30646629/163329b2-a43f-4668-908f-d4f9d8ad5ebd

**Comment by adithyaakrishna** [comment]
@joselimadev I will review this locally as well one more time just to be sure we don't have any other z-index issues

**Comment by adithyaakrishna** [comment]
Issue not reproducible anymore and confirmed with the below screenshot as well :)

Screenshot 2024-01-26 at 13 05 10

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎉

**Review by catalinpit — APPROVED** [review]
thanks for the work! great stuff!

**Review by dephraiim — APPROVED** [review]

**Pull request merged**
