### PR TITLE
feat: auto-scroll to next open-field while signing document

### LINKED ISSUE #710: [DOC-376] No jump to sign field
* When the user already has a signature in their account, the complete button is disabled, forcing them to scroll through the doc and click each field manually.
* When clicked on complete, the auto-scroll to open field should also be triggered.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-376](https://linear.app/documenso/issue/DOC-376/no-jump-to-sign-field)</sub>

### PR DESCRIPTION
**Pull request by ksushant6566**
resolves #710.

The complete button now takes the user to the next open-field. When all fields are done, opens confirmation dialog as usual.
attaching a loom below.

Edit: added a conditional on complete button to say `Skip to next field` when there are open fields and `Complete` otherwise.

https://www.loom.com/share/bb554acaa2b947139cd125e482910dd7?sid=85e37cd8-7f9a-4ce1-8a67-d3a82f5ea14b

### CODE REVIEW

**Comment by dguyen** [comment]
Hey @ksushant6566, could you make this trigger the tooltips in the parent component?

Something like when the dialog button is clicked & `isComplete` is false, you emit an event to the parent where it will validate the fields and display the tooltips.

**Comment by ksushant6566** [comment]
Hey @dguyen , made the requested changes; now the first open field shows a tooltip.

image


Also, the tooltips were overlapping with the header, so increased header's `z-index` as well

image

image

**Comment by ksushant6566** [comment]
I see the header z-index was already increased in a recent commit, so updated this

**Comment by catalinpit** [comment]
> I see the header z-index was already increased in a recent commit, so updated this

Hey @ksushant6566, thanks a lot for the work and the patience! I opened a PR to quickly make some changes and ship them asap. I added a link to your PR, since you and the other 2 authors did most of the work. Your work is very much appreciated.

I'll close this as a result. Thanks for understanding! 🙏

**Comment by ksushant6566** [comment]
No worries man, happy to help :)

**Pull request closed without merging**
