### PR TITLE
fix: able to login using forgot password #512

### LINKED ISSUE #512: Able to login using Forgot password
Description:

When I clicked on `Forgot your password?` and entered my email address, a password reset email arrived in my inbox. Ideally, it should have shown an "Email not found" error. However, I was able to set a new password and then login to the app without any issue.

Not sure whether it is the intended behaviour or a bug

Would you like to work on this?
Yes

### PR DESCRIPTION
**Pull request by 18feb06**
This PR fixes #512 

After Fix: [Watch after fix video](https://streamable.com/ucf5dm)

### CODE REVIEW

**Comment by dguyen** [comment]
Hey @18feb06, thanks for your contributions but you can't actually log in via forgot password so these changes will be redundant.

In regards to displaying "email doesn't exist", we prefer showing the current generic message instead, which implies that the email will be sent if it the account exists:

> A password reset email has been sent, if you have an account you should see it in your inbox shortly.

**Comment by 18feb06** [comment]
@mittalsam98 How can I assign issue to my self?
I am new to open source...Can you please guide me?

**Comment by dguyen** [comment]
@18feb06 you can't assign the issue to yourself, a team member will do it for you as long as you follow the contribution guidelines here:

https://github.com/documenso/documenso/blob/feat/refresh/CONTRIBUTING.md#taking-issues

Specifically the `taking-issues` section.

Please let us know if you have any questions! We are always happy to help :)

**Comment by 18feb06** [comment]
@dguyen OK thanks

**Pull request closed without merging**
