### PR TITLE
feat: sub-path based i18n

### PR DESCRIPTION
**Pull request by younes101020**
## Description

- [x] append lang sub-path when not specified to URL
- [x] read sub-path from server component for allowing server-side translations
- [x] add new `useDictionary` hook and `DictionaryProvider` provider for allowing client-side translations
- [x] complete "en" + "fr" translation
- [ ] add 2 or 3 new language translation

## Changes Made

Regarding dates and time I replaced the use of methods from the luxon library with those from the native Intl API

## Manual testing

- Test if lang sub-path is correctly appending when no specified
- Test to manually update lang sub-path
- Test that the translation fits the sub-path lang
- Tested on Chrome.

## Checklist

- [ x] I have tested these changes locally and they work as expected.
- [ x] I have added/updated tests that prove the effectiveness of these changes.
- [ ] I have updated the documentation to reflect these changes, if applicable.
- [ x] I have followed the project's coding style guidelines.
- [ ] I have addressed the code review feedback from the previous submission, if applicable.

## Additional Notes

this is my first open source participation so please don't hesitate if you have advice for me

## Summary by CodeRabbit

- **New Features**
  - Added internationalization support for English and French locales.
  - Introduced dynamic content rendering based on locale for various marketing pages and components.
  - Added a React context provider for managing dictionaries.

- **Bug Fixes**
  - Replaced hardcoded text with dynamic content fetched from dictionaries to support multiple languages.

- **Documentation**
  - Introduced new blog posts to explain features and improvements in Documenso.

- **Chores**
  - Updated dependencies to support internationalization features.

- **Refactor**
  - Modified several components to accept dictionary props for dynamic content rendering.
  - Introduced middleware for handling locale negotiation in a Next.js application.

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by younes101020** [comment]
> Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:
> 
> https://documen.so/cla

Hello it's done

**Comment by younes101020** [comment]
Hello @Mythie can you review my PR please ?

**Comment by dguyen** [comment]
Hey! Apologies, but we're already integrating an i18n solution which goes in a different direction than your implementation

Prior to large work like this, we recommend looking through issues or dropping into our discord to see if there's any ongoing work related to anything you would like to work on

**Pull request closed without merging**
