### PR TITLE
fix: safari pdf overflow issue fixed

### LINKED ISSUE #465: [BUG] [SAFARI] The document viewer has pdf overflow issue
Screenshot 2023-09-29 at 4 49 49 PM
Screenshot 2023-09-29 at 4 51 27 PM
Screenshot 2023-09-29 at 4 51 18 PM

### PR DESCRIPTION
**Pull request by hashkazi00**
Description:
This PR fixes #465

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by hashkazi00** [comment]
Done

> Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:
> 
> https://documen.so/cla

**Comment by ElTimuro** [comment]
image

**Comment by Mythie** [comment]
I'll get the conflict sorted and get this merged! Thanks so much 🙌

**Review by Mythie — APPROVED** [review]

**Comment by Mythie** [comment]
Thanks for your contribution 🎉 

its-done-frodo

**Pull request merged**
