### PR TITLE
fix: body exeeded undefined limit

### LINKED ISSUE #678: Uploading lager PDF throws "Body exceeded undefined limit." Error
### Issue Description

When uploading a lager document an error is thrown.

### Steps to Reproduce

Upload [testDocument.pdf](https://github.com/documenso/documenso/files/13447019/testDocument.pdf)

### Expected Behavior

_No response_

### Current Behavior

**Error**: Body exceeded undefined limit.
To configure the body size limit for Server Actions, see: https://nextjs.org/docs/app/api-reference/server-actions#size-limitation

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

Firefox

### Version [e.g., 2.0.1]

main (c054fc78a490302c7b05224a8b459ff8c1cdc019)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by david-loe**
fixes #678

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by david-loe** [comment]
Done

**Comment by Mythie** [comment]
Looks like we will also want this for the marketing `next.config.js` as well! Sorry for the delay 🫶🏻

**Review by catalinpit — APPROVED** [review]
looks good! thanks for making the changes!

**Pull request merged**
